#!/usr/bin/env bash
#      _       _    __ _ _
#   __| | ___ | |_ / _(_) | ___  ___
#  / _` |/ _ \| __| |_| | |/ _ \/ __|
# | (_| | (_) | |_|  _| | |  __/\__ \
#  \__,_|\___/ \__|_| |_|_|\___||___/
#
# This script link all the dotfiles in this directory
# to your home directory.

DOTFILES_SCRIPT="$(readlink -f "$0")"
DOTFILES_DIR="$(dirname "$DOTFILES_SCRIPT")"

DOTFILES="$(find "$DOTFILES_DIR" -type f | grep -v "\(.git\|README\|dotfiles$\|test\)")"
DOTFILES_DEPTH="$(($(echo -n "$DOTFILES_SCRIPT" | grep -o / | wc -l) + 1))"

while IFS= read -r TARGET; do
	LINK="$HOME/$(cut -d "/" -f "${DOTFILES_DEPTH}-" <<<"$TARGET")"

	echo "$LINK -> $TARGET"
	dirname "$LINK" | xargs mkdir -p
	ln -sf "$TARGET" "$LINK"

done <<<"$DOTFILES"
